/**
 * Maps INEGI state codes (1–32) to the canonical entidad_final values
 * stored in snii.researchers (uppercase, unaccented Spanish).
 */
export const STATE_CODE_TO_DB_NAME: Record<number, string> = {
  1: "AGUASCALIENTES",
  2: "BAJA CALIFORNIA",
  3: "BAJA CALIFORNIA SUR",
  4: "CAMPECHE",
  5: "COAHUILA DE ZARAGOZA",
  6: "COLIMA",
  7: "CHIAPAS",
  8: "CHIHUAHUA",
  9: "CIUDAD DE MEXICO",
  10: "DURANGO",
  11: "GUANAJUATO",
  12: "GUERRERO",
  13: "HIDALGO",
  14: "JALISCO",
  15: "MEXICO",
  16: "MICHOACAN DE OCAMPO",
  17: "MORELOS",
  18: "NAYARIT",
  19: "NUEVO LEON",
  20: "OAXACA",
  21: "PUEBLA",
  22: "QUERETARO",
  23: "QUINTANA ROO",
  24: "SAN LUIS POTOSI",
  25: "SINALOA",
  26: "SONORA",
  27: "TABASCO",
  28: "TAMAULIPAS",
  29: "TLAXCALA",
  30: "VERACRUZ DE IGNACIO DE LA LLAVE",
  31: "YUCATAN",
  32: "ZACATECAS",
};

export const STATE_DISPLAY_NAME: Record<number, string> = {
  1: "Aguascalientes",
  2: "Baja California",
  3: "Baja California Sur",
  4: "Campeche",
  5: "Coahuila",
  6: "Colima",
  7: "Chiapas",
  8: "Chihuahua",
  9: "Ciudad de México",
  10: "Durango",
  11: "Guanajuato",
  12: "Guerrero",
  13: "Hidalgo",
  14: "Jalisco",
  15: "México",
  16: "Michoacán",
  17: "Morelos",
  18: "Nayarit",
  19: "Nuevo León",
  20: "Oaxaca",
  21: "Puebla",
  22: "Querétaro",
  23: "Quintana Roo",
  24: "San Luis Potosí",
  25: "Sinaloa",
  26: "Sonora",
  27: "Tabasco",
  28: "Tamaulipas",
  29: "Tlaxcala",
  30: "Veracruz",
  31: "Yucatán",
  32: "Zacatecas",
};
